<a href="https://colab.research.google.com/github/PrathameshBagal/Data-Science/blob/main/Digit_Recognition_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Kaggle challenge and data : https://www.kaggle.com/competitions/digit-recognizer/overview


In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
data = pd.read_csv('train.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

In [ ]:
# In the df, the 0 th column was the label so now the 0th row will be the label
data_dev = data[:1000].T
X_dev = data_dev[1:n]
Y_dev= data_dev[0]
X_dev = X_dev / 255

data_train = data[1000:m].T
X_train = data_train[1:n]
Y_train= data_train[0]
X_train = X_train / 255

In [ ]:
def init_params():
    W1 = np.random.rand(10,784) -0.5
    B1 = np.random.rand(10,1)-0.5
    W2 = np.random.rand(10,10)-0.5
    B2 = np.random.rand(10,1)-0.5

    return W1,B1,W2,B2

def ReLU(Z):
    return np.maximum(0,Z)

def softmax(Z):
    A = np.exp(Z) / np.sum(np.exp(Z), axis=0)
    return A

def derivative_ReLU(Z1):
    return Z1>0

def forward_propogation(W1,b1,W2,b2,X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)

    return Z1,A1,Z2,A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_propogation(Z1,A1,Z2,A2,W1,W2,X,Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)

    dZ1 = W2.T.dot(dZ2) * derivative_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)

    return dW2,db2,dW1,db1

def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha):
    W1 = W1 - alpha*dW1
    b1 = b1 - alpha*db1
    W2 = W2 - alpha*dW2
    b2 = b2 - alpha*db2

    return W1,b1,W2,b2

def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions,Y):
    print(predictions, Y)
    return np.sum(predictions==Y)/Y.size

def gradient_descent(X,Y,iterations,alpha):
    W1,b1,W2,b2 = init_params()
    for i in range(iterations):
        Z1,A1,Z2,A2 = forward_propogation(W1,b1,W2,b2,X)
        dW2,db2,dW1,db1 = backward_propogation(Z1,A1,Z2,A2,W1,W2,X,Y)
        W1,b1,W2,b2 = update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha)

        if i%10==0:
            print(f"Iteration : {i}")
            print(get_accuracy(get_predictions(A2),Y))
    return W1,b1,W2,b2


In [ ]:
W1,b1,W2,b2 = gradient_descent(X_train,Y_train,500,0.1)

Iteration : 0
[1 0 0 ... 0 1 1] [3 7 6 ... 3 1 6]
0.13275609756097562
Iteration : 10
[6 0 7 ... 7 1 1] [3 7 6 ... 3 1 6]
0.21953658536585366
Iteration : 20
[6 7 7 ... 3 1 0] [3 7 6 ... 3 1 6]
0.28107317073170734
Iteration : 30
[6 7 7 ... 3 1 0] [3 7 6 ... 3 1 6]
0.3288048780487805
Iteration : 40
[6 7 7 ... 3 1 0] [3 7 6 ... 3 1 6]
0.37114634146341463
Iteration : 50
[4 7 7 ... 3 1 3] [3 7 6 ... 3 1 6]
0.4131463414634146
Iteration : 60
[4 7 7 ... 3 1 4] [3 7 6 ... 3 1 6]
0.45519512195121953
Iteration : 70
[4 7 7 ... 3 1 4] [3 7 6 ... 3 1 6]
0.49746341463414634
Iteration : 80
[6 7 2 ... 3 1 6] [3 7 6 ... 3 1 6]
0.5353414634146342
Iteration : 90
[6 7 2 ... 3 1 6] [3 7 6 ... 3 1 6]
0.5674634146341463
Iteration : 100
[6 7 2 ... 3 1 6] [3 7 6 ... 3 1 6]
0.5952439024390244
Iteration : 110
[6 7 2 ... 3 1 6] [3 7 6 ... 3 1 6]
0.6219268292682927
Iteration : 120
[6 7 2 ... 3 1 6] [3 7 6 ... 3 1 6]
0.641609756097561
Iteration : 130
[8 7 2 ... 3 1 6] [3 7 6 ... 3 1 6]
0.6581951219512195
Iteration : 